# Config file for automatic testing at travis-ci.org

# Run in Python 3 only. Drop Python 2 testing
language: python
python:
  - 3.8
  - 3.9

dist: jammy

before_install:
  - python --version

install:
  - pip install -U pip pytest spacy coverage flake8
  # Set up variables
  - export BRANCH=$TRAVIS_BRANCH

script:
  - flake8
  - python -m spacy download en_core_web_sm
  - python -m spacy download en_core_web_md
  - python -m spacy download en_core_web_lg
  - coverage run -m pytest
  - coverage report -m
